local colors = {
  bg = '#2e3440',
  blue = '#5e81ac',
  blue_dark = '#4c6a8f',
  blue_light = '#7693b8',
  cyan = '#88c0d0',
  cyan_dark = '#76a7b5',
  cyan_light = '#99c9d6',
  fg = '#ECEFF4',
  green = '#a3be8c',
  green_dark = '#8fa77a',
  green_light = '#b1c89d',
  grey1 = '#f8fafc',
  grey10 = '#616d85',
  grey11 = '#464f62',
  grey12 = '#3a4150',
  grey13 = '#333a47',
  grey14 = '#242932',
  grey15 = '#1e222a',
  grey16 = '#1c1f26',
  grey17 = '#0f1115',
  grey18 = '#0d0e11',
  grey19 = '#020203',
  grey2 = '#f0f1f4',
  grey3 = '#eaecf0',
  grey4 = '#d9dce3',
  grey5 = '#c4c9d4',
  grey6 = '#b5bcc9',
  grey7 = '#929cb0',
  grey8 = '#8e99ae',
  grey9 = '#74819a',
  magenta = '#b48ead',
  magenta_dark = '#9c7a95',
  magenta_light = '#c0a0b9',
  orange = '#d08770',
  orange_dark = '#b67663',
  orange_light = '#958784',
  pink = '#FFA19F',
  pink_dark = '#e68f8d',
  pink_light = '#ffb3b1',
  red = '#bf616a',
  red_dark = '#a6545c',
  red_light = '#c57078',
  yellow = '#ebcb8b',
  yellow_dark = '#d4b67e',
  yellow_light = '#f2d89d',
}

return {
  {
    'rmehri01/onenord.nvim',
    lazy = false,
    priority = 10000,
    opts = {
      borders = false,
      fade_nc = true,
      styles = {
        comments = 'italic',
        strings = 'NONE',
        keywords = 'NONE',
        functions = 'italic',
        variables = 'bold',
        diagnostics = 'underline',
      },
      disable = {
        background = false,

        cursorline = false,
        eob_lines = true,
      },
      custom_highlights = {
        WhichKeyFloat = { bg = colors.grey14 },

        GitSignsAdd = { fg = colors.green },
        GitSignsChange = { fg = colors.orange },
        GitSignsDelete = { fg = colors.red },

        -- NvimTreeFolderIcon = { fg = colors.grey9 },
        -- NvimTreeIndentMarker = { fg = colors.grey12 },
        -- NvimTreeNormal = { fg = colors.grey5, bg = colors.grey14 },

        NormalFloat = { bg = colors.grey14 },
        FloatBorder = { bg = colors.grey14, fg = colors.grey14 },

        FzfLuaNormal = { fg = colors.blue, bg = colors.grey16 },
        FzfLuaBorder = { bg = colors.grey16, fg = colors.grey14 },
        FzfLuaCursor = { fg = colors.blue },
        FzfLuaCursorLine = { fg = colors.blue },
        FzfLuaCursorLineNr = { fg = colors.blue },
        FzfLuaPreviewNormal = { fg = colors.grey16, bg = colors.grey16 },
        FzfLuaPreviewBorder = { fg = colors.grey16, bg = colors.grey16 },
        FzfLuaTitle = { fg = colors.blue, bg = colors.grey16 },
        FzfLuaPreviewTitle = { fg = colors.blue },
        FzfLuaFzfPrompt = { fg = colors.yellow },
        FzfLuaFzfMarker = { fg = colors.yellow },
        FzfLuaFzfPointer = { fg = colors.yellow },
        FzfLuaBackdrop = { bg = colors.grey14 },

        BlinkCmpKind = { fg = colors.blue },

        BlinkCmpKindFile = { fg = colors.blue },
        BlinkCmpKindText = { fg = colors.green },
        BlinkCmpKindUnit = { fg = colors.cyan },
        BlinkCmpKindClass = { fg = colors.orange },
        BlinkCmpKindColor = { fg = colors.red },
        BlinkCmpKindEvent = { fg = colors.pink },
        BlinkCmpKindField = { fg = colors.yellow },
        BlinkCmpKindValue = { fg = colors.magenta_light },
        BlinkCmpKindFolder = { fg = colors.blue_light },
        BlinkCmpKindMethod = { fg = colors.magenta },
        BlinkCmpKindModule = { fg = colors.orange_dark },
        BlinkCmpKindStruct = { fg = colors.pink_dark },
        BlinkCmpKindKeyword = { fg = colors.red_light },
        BlinkCmpKindSnippet = { fg = colors.cyan_light },
        BlinkCmpLabelDetail = { fg = colors.green_dark },
        BlinkCmpKindConstant = { fg = colors.yellow_dark },
        BlinkCmpKindFunction = { fg = colors.magenta_dark },
        BlinkCmpKindOperator = { fg = colors.red_dark },
        BlinkCmpKindProperty = { fg = colors.yellow_light },
        BlinkCmpKindVariable = { fg = colors.cyan_dark },
        BlinkCmpKindInterface = { fg = colors.green_light },
        BlinkCmpKindReference = { fg = colors.pink_light },
        BlinkCmpKindEnumMember = { fg = colors.orange_dark },
        BlinkCmpKindConstructor = { fg = colors.pink_dark },

        BlinkCmpSourceLsp = { fg = colors.pink },

        TelescopePromptPrefix = { bg = colors.grey14 },
        TelescopePromptNormal = { bg = colors.grey14 },
        TelescopeResultsNormal = { bg = colors.grey15 },
        TelescopePreviewNormal = { bg = colors.grey16 },
        TelescopePromptBorder = { bg = colors.grey14, fg = colors.grey14 },
        TelescopeResultsBorder = { bg = colors.grey15, fg = colors.grey15 },
        TelescopePreviewBorder = { bg = colors.grey16, fg = colors.grey16 },
        TelescopePromptTitle = { fg = colors.grey14 },
        TelescopeResultsTitle = { fg = colors.grey15 },
        TelescopePreviewTitle = { fg = colors.grey16 },

        PmenuSel = { bg = colors.grey12 },
        Pmenu = { bg = colors.grey14 },
        PMenuThumb = { bg = colors.grey16 },

        LspFloatWinNormal = { fg = colors.fg, bg = colors.grey14 },
        LspFloatWinBorder = { fg = colors.grey14 },

        NoiceCmdlineIconCmdline = { fg = colors.yellow },
        NoiceCmdlineIconLua = { fg = colors.magenta },
        NoiceCmdlineIconSearch = { fg = colors.magenta },
        NoiceCmdlineIconHelp = { fg = colors.blue },
        NoiceCmdlinePopupBorder = { bg = colors.grey14, fg = colors.grey14 },
        NoiceCmdlinePopupBorderCmdline = { bg = colors.grey14, fg = colors.grey14 },
        NoiceCmdlinePopupBorderLua = { bg = colors.grey14, fg = colors.grey14 },
        NoiceCmdlinePopupBorderSearch = { bg = colors.grey14, fg = colors.grey14 },
        NoiceCmdlinePopupBorderHelp = { bg = colors.grey14, fg = colors.grey14 },
        NoiceCmdlinePopupBorderFilter = { bg = colors.grey14, fg = colors.grey14 },
        NoiceCmdlinePopupBorderInput = { bg = colors.grey14, fg = colors.grey14 },

        AlphaHeader = { fg = colors.yellow },
        AlphaShortcut = { fg = colors.magenta, style = 'italic' },
        AlphaButtons = { fg = colors.grey1 },
        AlphaFooter = { fg = colors.orange, style = 'italic' },

        NeoTreeCursorLine = { bg = colors.grey11 },
      },
    },
  },
  -- Configure LazyVim to load onenord
  {
    'LazyVim/LazyVim',
    opts = {
      colorscheme = 'onenord',
    },
  },
}
